require:
  # - rubocop-packaging
  - rubocop-performance

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Lint/NestedMethodDefinition:
  Enabled: false

Layout/RescueEnsureAlignment:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false
